version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - dev

image: Ubuntu2004

platform: Any CPU

configuration: Release

build_script:
  - ./make.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS_DOXYGEN=OFF 
