version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - dev

image: Ubuntu2004

install:
- ls -al
- sh: sudo apt-get update && sudo apt-get install ninja-build libboost-all-dev openssl libomp-dev libopencv-dev libssl-dev openssl libsfml-dev nvidia-cuda-dev nvidia-cuda-toolkit freeglut3-dev qt5-default qtmultimedia5-dev qtbase5-dev-tools qtdeclarative5-dev mesa-common-dev libpcap-dev lld ocl-icd-opencl-dev ocl-icd-libopencl1 opencl-headers

platform: Any CPU

configuration: Release

build_script:
  - ./make.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS_DOXYGEN=OFF 
