ARG IMAGE=ubuntu:20.04

FROM $IMAGE
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \ 
    && apt-get install -y --allow-unauthenticated \ 
    hello \ 
    && apt clean -y \ 
    && apt autoclean -y \ 
    && apt autoremove -y \ 
    && rm -rf /var/lib/apt/lists/*

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000
#RUN groupadd -g $GID -o $UNAME
#RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
#USER $UNAME

WORKDIR /usr/src/app
CMD ./make.sh -DCMAKE_BUILD_TYPE=Release
