ARG IMAGE=fedora:33

FROM $IMAGE

RUN dnf upgrade -y --refresh && dnf install -y gcc boost opencv opencv-devel cmake ninja-build gcc-c++ \
    git freeglut-devel xorg-x11-apps libudev-devel libXrandr libXrandr-devel libX11 \
    qt5-qtbase-devel qt5-qtbase openal-soft vorbis-tools libvorbis openal-soft-devel openssl SFML-devel \
    boost-devel openssl-devel qt5-qtmultimedia-devel qt5-qtquickcontrols2-devel && dnf autoremove -y
RUN dnf install -y qt5-qtmultimedia qt5-qtquickcontrols2 qt5-qtquickcontrols

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME && useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME

WORKDIR /usr/src/app
CMD ./make.sh -DCMAKE_BUILD_TYPE=Release
 

