ARG IMAGE=archlinux

FROM $IMAGE
ADD config_docker/pacman.conf /etc/pacman.conf
RUN pacman -Syyu --noconfirm && pacman -S sfml boost opencv-samples opencv gcc freeglut \ 
 cmake ninja qt5-base qt5-tools qt5-quickcontrols2 qt5-multimedia qt5-3d qt5-quick3d hdf5 vtk opencl-icd-loader vulkan-icd-loader --noconfirm && pacman -Scc --noconfirm

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME && useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME

WORKDIR /usr/src/app
CMD ./make.sh -DCMAKE_BUILD_TYPE=Release
 
