ARG IMAGE=ubuntu:20.04

FROM $IMAGE
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \ 
    && apt-get install -y --allow-unauthenticated \ 
    libsfml-dev ninja-build libopencv-dev qml-module-qtquick-controls qml-module-qtquick-controls2 \ 
    g++ build-essential cmake qt5-default qtmultimedia5-dev mesa-common-dev libpcap-dev libssl-dev cppcheck ocl-icd-libopencl1 opencl-headers \ 
    freeglut3-dev libboost-all-dev qtbase5-dev-tools qtdeclarative5-dev libqt5multimedia5 openssl libomp-dev lld nvidia-cuda-dev nvidia-cuda-toolkit ocl-icd-opencl-dev \ 
    && apt clean -y \ 
    && apt autoclean -y \ 
    && apt autoremove -y \ 
    && rm -rf /var/lib/apt/lists/*
