name: Dockcross CI BenLib

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'build/**'
      - '**.md'
      - 'appveyor.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'build/**'
      - '**.md'
      - 'appveyor.yml'

jobs:
  image:
    name: ${{ matrix.arch_name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch_name: [android-arm, android-arm64, android-x86, android-x86_64, web-wasm, linux-arm64, linux-arm64-musl, linux-armv5, linux-armv5-musl, linux-armv6, linux-armv6-musl, linux-armv7, linux-armv7a, linux-armv7l-musl, linux-s390x, linux-x64, linux-x86, manylinux1-x64, manylinux1-x86, manylinux2010-x64, manylinux2010-x86, manylinux2014-x64, manylinux2014-x86, manylinux2014-aarch64, windows-static-x64, windows-static-x64-posix, windows-static-x86, windows-shared-x64, windows-shared-x64-posix, windows-shared-x86]
    steps:
      - name: "游닌 Checkout Code"
        uses: actions/checkout@v2.2.0
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: "游닌 Install Docker"
        run: sudo apt-get update && sudo apt-get remove docker docker-engine docker.io containerd runc && sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
      
      - name: "游닌 Install Docker"
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: "游닌 Install Docker"
        run: sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Create script
        run: docker run --rm dockcross/${{ matrix.arch_name }} > ./dockcross-${{ matrix.arch_name }} && chmod +x ./dockcross-${{ matrix.arch_name }}

      - name: CMAKE
        run: ./dockcross-${{ matrix.arch_name }} cmake -Bbuild_${{ matrix.arch_name }} -H. -GNinja

      - name: CMAKE
        run: ./dockcross-${{ matrix.arch_name }} ninja -Cbuild_${{ matrix.arch_name }}